LangString addOrReinstall ${LANG_CZECH} "Přeinstalovat"
LangString alreadyInstalled ${LANG_CZECH} "Již nainstalováno"
LangString alreadyInstalledLong ${LANG_CZECH} "${PRODUCTNAME} ${VERSION} je již nainstalován. Vyberte, co chcete udělat, a pokračujte tlačítkem Další."
LangString appRunning ${LANG_CZECH} "${PRODUCTNAME} je spuštěný. Nejdřív ho ukončete a zkuste to znovu."
LangString appRunningOkKill ${LANG_CZECH} "${PRODUCTNAME} je spuštěný.$\nKliknutím na OK ho ukončíte."
LangString chooseMaintenanceOption ${LANG_CZECH} "Vyberte akci, kterou chcete provést."
LangString choowHowToInstall ${LANG_CZECH} "Vyberte, jak chcete ${PRODUCTNAME} nainstalovat."
LangString createDesktop ${LANG_CZECH} "Vytvořit zástupce na ploše"
LangString dontUninstall ${LANG_CZECH} "Neodinstalovat"
LangString dontUninstallDowngrade ${LANG_CZECH} "Neodinstalovat (instalace starší verze bez odinstalace není povolena)"
LangString failedToKillApp ${LANG_CZECH} "${PRODUCTNAME} se nepodařilo ukončit. Ukončete ho ručně a zkuste to znovu."
LangString installingWebview2 ${LANG_CZECH} "Instaluji WebView2…"
LangString newerVersionInstalled ${LANG_CZECH} "Je nainstalována novější verze ${PRODUCTNAME}. Instalace starší verze se nedoporučuje. Pokud ji opravdu chcete, nejdřív odinstalujte aktuální verzi. Vyberte, co chcete udělat, a pokračujte tlačítkem Další."
LangString older ${LANG_CZECH} "starší"
LangString olderOrUnknownVersionInstalled ${LANG_CZECH} "V počítači je nainstalována $R4 verze ${PRODUCTNAME}. Doporučujeme ji před instalací odinstalovat. Vyberte, co chcete udělat, a pokračujte tlačítkem Další."
LangString silentDowngrades ${LANG_CZECH} "Instalace starší verze je v tomto instalátoru zakázaná a tichou instalaci nelze dokončit. Použijte prosím instalátor s grafickým rozhraním.$\n"
LangString unableToUninstall ${LANG_CZECH} "Odinstalace se nezdařila."
LangString uninstallApp ${LANG_CZECH} "Odinstalovat ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CZECH} "Před instalací odinstalovat"
LangString unknown ${LANG_CZECH} "neznámá"
LangString webview2AbortError ${LANG_CZECH} "Instalace WebView2 se nezdařila. Aplikace bez něj nefunguje. Zkuste instalátor spustit znovu."
LangString webview2DownloadError ${LANG_CZECH} "Chyba: stažení WebView2 se nezdařilo – $0"
LangString webview2DownloadSuccess ${LANG_CZECH} "Instalátor WebView2 byl stažen"
LangString webview2Downloading ${LANG_CZECH} "Stahuji instalátor WebView2…"
LangString webview2InstallError ${LANG_CZECH} "Chyba: instalace WebView2 skončila kódem $1"
LangString webview2InstallSuccess ${LANG_CZECH} "WebView2 byl nainstalován"
LangString deleteAppData ${LANG_CZECH} "Smazat data aplikace"
